[pytest]

addopts = --html=./reports/report.html --tb=long -v -s
pythonpath = .
testpaths = ./api-test/test_cases ./ui-test/test_cases
markers =
    smoke: 冒烟测试
    regression: 回归测试
    ui: UI测试
    api: 接口测试
    rbac: 权限控制测试
    auth: 鉴权相关测试