[pytest]

addopts = --html=./reports/report.html --tb=long -v -s
pythonpath = .
testpaths = ./api_test/test_cases ./ui_test/test_cases
markers =
    smoke: 冒烟测试
    login: 登录相关测试
    regression: 回归测试
    ui: UI测试
    api: 接口测试
    rbac: 权限控制测试
    auth: 鉴权相关测试
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True